apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.128.0.5
  selector:
    app: app
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 8080
